#!/bin/bash

########################################################################################################################

source local_paths.sh

export PATH="$PY3ENV:$PATH"
export PYTHONPATH="$LOCAL/py3:$SCRIPTS/py3:$PYTHONPATH"
export LD_LIBRARY_PATH=/usr/local/lib:/home/alon/dev/cplex128/bin/x86-64_linux

ipython -i "$@"

########################################################################################################################
