#!/bin/bash

source local_paths.sh

export PATH="$HOME/dev/envp/bin:$PATH"

export PYTHONPATH="$SCRIPTS/py2:$RESEARCH:$ROOT/euclid/sdk:$PYTHONPATH"

pip "$@"

########################################################################################################################
