#!/bin/bash

source bash_utils.sh

export PATH="$HOME/dev/envp/bin:$PATH"

export PYTHONPATH="$SCRIPTS/py2:$RESEARCH:$PYTHONPATH"

python "$@"

########################################################################################################################
