#!/bin/bash

source local_paths.sh

export PATH="$HOME/dev/venv/bin:$PATH"
export PYTHONPATH="$SCRIPTS/py2:$RESEARCH:$ROOT/euclid/sdk:$PYTHONPATH"
export LD_LIBRARY_PATH=/usr/local/lib:/home/alon/dev/cplex128/bin/x86-64_linux

python "$@"

########################################################################################################################
